import React from "react"
import { Container, Row, Col } from "reactstrap"
import { Helmet } from "react-helmet"
import Nav from "../../components/Nav/nav"
import InnerContent from "../../components/innerContent/innerContent"
import Footer from "../../components/Footer/footer"
import Hero from "../../components/Home/Hero/Hero"
import aboutImg from "../img/about.jpg"
import "../scss/about.scss"

const About = () => {
  return (
    <>
      <Helmet>
        <title>About - Plant No. 1</title>
        <meta
          name="description"
          content="We offer a creative line-up of plant based comfort foods, and
                  yes, because we love desserts, we have a pretty awesome
                  selection of that too. We use the best ingredients we can
                  find, void of anything artificial, hydrogenated or
                  genetically modified."
        />
      </Helmet>
      <Nav />
      <Hero
        title="We are a zero waste “vegan food factory” located in NIagara-on-the-Lake, Ontario, just a few minutes off the QEW highway. "
        subtitle="About"
      />
      <InnerContent>
        <section className="about">
          <Container>
            {/* One */}
            <Row>
              <Col lg="6">
                <p>
                  We offer a creative line-up of plant based comfort foods, and
                  yes, because we love desserts, we have a pretty awesome
                  selection of that too. We use the best ingredients we can
                  find, void of anything artificial or hydrogenated or
                  genetically modified.
                  <br />
                  <br />
                  Our goal is to provide plant based meals that appeal to both
                  herbivores and carnivores alike. Need lunch or dinner and
                  don’t want to shop, cook, or clean? Come on over and check us
                  out!
                </p>
                <p>
                  All food is made in-house and available in our outlet store at
                  the front of our kitchen facility. We offer a wide array of
                  our own frozen entrees and desserts as well as a limited (but
                  fabulous) selection of our frozen options , ready-to-eat , for
                  lunch and dinner.
                </p>
              </Col>
              <Col lg="6">
                <img className="img-fluid" src={aboutImg} alt="about" />
              </Col>
            </Row>
            <Row>
              <Col lg="12">
                <br />
                <h2>On a side note...</h2>
                <p>
                  Plant No. 1 is a pretty interesting place (literally built
                  from the ground up).. We try to run (mostly) on solar power,
                  we recycle grey water from our roof to take care of our
                  outdoor landscaping, packaging is compostable or biodegradable
                  right down to the labels (please,please pack all of your food
                  items from Plant No. 01 in your compost bin at work or at home
                  ) and we compost almost every bit of waste generated by our
                  facility...down to one bag of garbage...I think we can do it!
                  <br />
                  <br />
                  We are all about respect for this beautiful planet, the human
                  race, and all things living.
                </p>
              </Col>
            </Row>
          </Container>
        </section>
      </InnerContent>
      <Footer />
    </>
  )
}

export default About
